install.packages('rmarkdown')
install.packages("dplyr")
install.packages("readr")
install.packages("knitr")
install.packages("kableExtra")
install.packages("tidyr")
install.packages("ggplot2")

library(ggplot2)
library(tidyr)
library(kableExtra)
library(knitr)
library(rmarkdown)
library(dplyr)
library(readr)